import localFont from "next/font/local";
import "./globals.css";
import Header from "../components/Header.jsx";
import Footer from "@/components/Footer";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Kumaon Palaza",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-customBg`}
      >
        <div className="flex flex-col min-h-screen relative overflow-visible">
          <Header />
          <main className="flex-grow">{children}</main>
        </div>
        <Footer className="fixed bottom-0 left-0 w-full" />
      </body>
    </html>
  );
}
